export const SCREENS = {
  1: '640px',
  2: '768px',
  3: '1024px',
  4: '1280px',
} as const;

export const THEMES = {
  DARK: 'dark-theme',
  DEFAULT: 'default-theme',
  BLUE: 'blue-theme',
  GREEN: 'green-theme',
  YELLOW: 'yellow-theme',
} as const;

export const POKEBALL = [
  {
    theme: THEMES.DEFAULT,
    path: 'src/assets/themeIcons/red.png',
  },
  { theme: THEMES.BLUE, path: 'src/assets/themeIcons/blue.png' },
  {
    theme: THEMES.GREEN,
    path: 'src/assets/themeIcons/green.png',
  },
  { theme: THEMES.DARK, path: 'src/assets/themeIcons/white.png' },
  {
    theme: THEMES.YELLOW,
    path: 'src/assets/themeIcons/gold.png',
  },
];

export const TYPES = [
  'normal',
  'fire',
  'water',
  'grass',
  'electric',
  'ice',
  'fighting',
  'poison',
  'ground',
  'flying',
  'psychic',
  'bug',
  'rock',
  'ghost',
  'dark',
  'dragon',
  'steel',
  'fairy',
] as const;

export enum GenEnum {
  GEN_1 = 151,
  GEN_2 = 251,
  GEN_3 = 386,
  GEN_4 = 494,
  GEN_5 = 649,
  GEN_6 = 721,
  GEN_7 = 809,
}

export const LIMIT_OFFSET = 6;

export const TEAM_GARY = [
  65, 130, 59, 3, 85, 34, 76, 125, 127, 22, 31, 51, 99, 101, 103, 136,
];

export const NEW_USER = [
  { name: 'bulbasaur', isCaught: false },
  { name: 'ivysaur', isCaught: false },
  { name: 'venusaur', isCaught: false },
  { name: 'charmander', isCaught: false },
  { name: 'charmeleon', isCaught: false },
  { name: 'charizard', isCaught: false },
  { name: 'squirtle', isCaught: false },
  { name: 'wartortle', isCaught: false },
  { name: 'blastoise', isCaught: false },
  { name: 'caterpie', isCaught: false },
  { name: 'metapod', isCaught: false },
  { name: 'butterfree', isCaught: false },
  { name: 'weedle', isCaught: false },
  { name: 'kakuna', isCaught: false },
  { name: 'beedrill', isCaught: false },
  { name: 'pidgey', isCaught: false },
  { name: 'pidgeotto', isCaught: false },
  { name: 'pidgeot', isCaught: false },
  { name: 'rattata', isCaught: false },
  { name: 'raticate', isCaught: false },
  { name: 'spearow', isCaught: false },
  { name: 'fearow', isCaught: false },
  { name: 'ekans', isCaught: false },
  { name: 'arbok', isCaught: false },
  { name: 'pikachu', isCaught: false },
  { name: 'raichu', isCaught: false },
  { name: 'sandshrew', isCaught: false },
  { name: 'sandslash', isCaught: false },
  { name: 'nidoran-f', isCaught: false },
  { name: 'nidorina', isCaught: false },
  { name: 'nidoqueen', isCaught: false },
  { name: 'nidoran-m', isCaught: false },
  { name: 'nidorino', isCaught: false },
  { name: 'nidoking', isCaught: false },
  { name: 'clefairy', isCaught: false },
  { name: 'clefable', isCaught: false },
  { name: 'vulpix', isCaught: false },
  { name: 'ninetales', isCaught: false },
  { name: 'jigglypuff', isCaught: false },
  { name: 'wigglytuff', isCaught: false },
  { name: 'zubat', isCaught: false },
  { name: 'golbat', isCaught: false },
  { name: 'oddish', isCaught: false },
  { name: 'gloom', isCaught: false },
  { name: 'vileplume', isCaught: false },
  { name: 'paras', isCaught: false },
  { name: 'parasect', isCaught: false },
  { name: 'venonat', isCaught: false },
  { name: 'venomoth', isCaught: false },
  { name: 'diglett', isCaught: false },
  { name: 'dugtrio', isCaught: false },
  { name: 'meowth', isCaught: false },
  { name: 'persian', isCaught: false },
  { name: 'psyduck', isCaught: false },
  { name: 'golduck', isCaught: false },
  { name: 'mankey', isCaught: false },
  { name: 'primeape', isCaught: false },
  { name: 'growlithe', isCaught: false },
  { name: 'arcanine', isCaught: false },
  { name: 'poliwag', isCaught: false },
  { name: 'poliwhirl', isCaught: false },
  { name: 'poliwrath', isCaught: false },
  { name: 'abra', isCaught: false },
  { name: 'kadabra', isCaught: false },
  { name: 'alakazam', isCaught: false },
  { name: 'machop', isCaught: false },
  { name: 'machoke', isCaught: false },
  { name: 'machamp', isCaught: false },
  { name: 'bellsprout', isCaught: false },
  { name: 'weepinbell', isCaught: false },
  { name: 'victreebel', isCaught: false },
  { name: 'tentacool', isCaught: false },
  { name: 'tentacruel', isCaught: false },
  { name: 'geodude', isCaught: false },
  { name: 'graveler', isCaught: false },
  { name: 'golem', isCaught: false },
  { name: 'ponyta', isCaught: false },
  { name: 'rapidash', isCaught: false },
  { name: 'slowpoke', isCaught: false },
  { name: 'slowbro', isCaught: false },
  { name: 'magnemite', isCaught: false },
  { name: 'magneton', isCaught: false },
  { name: 'farfetchd', isCaught: false },
  { name: 'doduo', isCaught: false },
  { name: 'dodrio', isCaught: false },
  { name: 'seel', isCaught: false },
  { name: 'dewgong', isCaught: false },
  { name: 'grimer', isCaught: false },
  { name: 'muk', isCaught: false },
  { name: 'shellder', isCaught: false },
  { name: 'cloyster', isCaught: false },
  { name: 'gastly', isCaught: false },
  { name: 'haunter', isCaught: false },
  { name: 'gengar', isCaught: false },
  { name: 'onix', isCaught: false },
  { name: 'drowzee', isCaught: false },
  { name: 'hypno', isCaught: false },
  { name: 'krabby', isCaught: false },
  { name: 'kingler', isCaught: false },
  { name: 'voltorb', isCaught: false },
  { name: 'electrode', isCaught: false },
  { name: 'exeggcute', isCaught: false },
  { name: 'exeggutor', isCaught: false },
  { name: 'cubone', isCaught: false },
  { name: 'marowak', isCaught: false },
  { name: 'hitmonlee', isCaught: false },
  { name: 'hitmonchan', isCaught: false },
  { name: 'lickitung', isCaught: false },
  { name: 'koffing', isCaught: false },
  { name: 'weezing', isCaught: false },
  { name: 'rhyhorn', isCaught: false },
  { name: 'rhydon', isCaught: false },
  { name: 'chansey', isCaught: false },
  { name: 'tangela', isCaught: false },
  { name: 'kangaskhan', isCaught: false },
  { name: 'horsea', isCaught: false },
  { name: 'seadra', isCaught: false },
  { name: 'goldeen', isCaught: false },
  { name: 'seaking', isCaught: false },
  { name: 'staryu', isCaught: false },
  { name: 'starmie', isCaught: false },
  { name: 'mr-mime', isCaught: false },
  { name: 'scyther', isCaught: false },
  { name: 'jynx', isCaught: false },
  { name: 'electabuzz', isCaught: false },
  { name: 'magmar', isCaught: false },
  { name: 'pinsir', isCaught: false },
  { name: 'tauros', isCaught: false },
  { name: 'magikarp', isCaught: false },
  { name: 'gyarados', isCaught: false },
  { name: 'lapras', isCaught: false },
  { name: 'ditto', isCaught: false },
  { name: 'eevee', isCaught: false },
  { name: 'vaporeon', isCaught: false },
  { name: 'jolteon', isCaught: false },
  { name: 'flareon', isCaught: false },
  { name: 'porygon', isCaught: false },
  { name: 'omanyte', isCaught: false },
  { name: 'omastar', isCaught: false },
  { name: 'kabuto', isCaught: false },
  { name: 'kabutops', isCaught: false },
  { name: 'aerodactyl', isCaught: false },
  { name: 'snorlax', isCaught: false },
  { name: 'articuno', isCaught: false },
  { name: 'zapdos', isCaught: false },
  { name: 'moltres', isCaught: false },
  { name: 'dratini', isCaught: false },
  { name: 'dragonair', isCaught: false },
  { name: 'dragonite', isCaught: false },
  { name: 'mewtwo', isCaught: false },
  { name: 'mew', isCaught: false },
  { name: 'chikorita', isCaught: false },
  { name: 'bayleef', isCaught: false },
  { name: 'meganium', isCaught: false },
  { name: 'cyndaquil', isCaught: false },
  { name: 'quilava', isCaught: false },
  { name: 'typhlosion', isCaught: false },
  { name: 'totodile', isCaught: false },
  { name: 'croconaw', isCaught: false },
  { name: 'feraligatr', isCaught: false },
  { name: 'sentret', isCaught: false },
  { name: 'furret', isCaught: false },
  { name: 'hoothoot', isCaught: false },
  { name: 'noctowl', isCaught: false },
  { name: 'ledyba', isCaught: false },
  { name: 'ledian', isCaught: false },
  { name: 'spinarak', isCaught: false },
  { name: 'ariados', isCaught: false },
  { name: 'crobat', isCaught: false },
  { name: 'chinchou', isCaught: false },
  { name: 'lanturn', isCaught: false },
  { name: 'pichu', isCaught: false },
  { name: 'cleffa', isCaught: false },
  { name: 'igglybuff', isCaught: false },
  { name: 'togepi', isCaught: false },
  { name: 'togetic', isCaught: false },
  { name: 'natu', isCaught: false },
  { name: 'xatu', isCaught: false },
  { name: 'mareep', isCaught: false },
  { name: 'flaaffy', isCaught: false },
  { name: 'ampharos', isCaught: false },
  { name: 'bellossom', isCaught: false },
  { name: 'marill', isCaught: false },
  { name: 'azumarill', isCaught: false },
  { name: 'sudowoodo', isCaught: false },
  { name: 'politoed', isCaught: false },
  { name: 'hoppip', isCaught: false },
  { name: 'skiploom', isCaught: false },
  { name: 'jumpluff', isCaught: false },
  { name: 'aipom', isCaught: false },
  { name: 'sunkern', isCaught: false },
  { name: 'sunflora', isCaught: false },
  { name: 'yanma', isCaught: false },
  { name: 'wooper', isCaught: false },
  { name: 'quagsire', isCaught: false },
  { name: 'espeon', isCaught: false },
  { name: 'umbreon', isCaught: false },
  { name: 'murkrow', isCaught: false },
  { name: 'slowking', isCaught: false },
  { name: 'misdreavus', isCaught: false },
  { name: 'unown', isCaught: false },
  { name: 'wobbuffet', isCaught: false },
  { name: 'girafarig', isCaught: false },
  { name: 'pineco', isCaught: false },
  { name: 'forretress', isCaught: false },
  { name: 'dunsparce', isCaught: false },
  { name: 'gligar', isCaught: false },
  { name: 'steelix', isCaught: false },
  { name: 'snubbull', isCaught: false },
  { name: 'granbull', isCaught: false },
  { name: 'qwilfish', isCaught: false },
  { name: 'scizor', isCaught: false },
  { name: 'shuckle', isCaught: false },
  { name: 'heracross', isCaught: false },
  { name: 'sneasel', isCaught: false },
  { name: 'teddiursa', isCaught: false },
  { name: 'ursaring', isCaught: false },
  { name: 'slugma', isCaught: false },
  { name: 'magcargo', isCaught: false },
  { name: 'swinub', isCaught: false },
  { name: 'piloswine', isCaught: false },
  { name: 'corsola', isCaught: false },
  { name: 'remoraid', isCaught: false },
  { name: 'octillery', isCaught: false },
  { name: 'delibird', isCaught: false },
  { name: 'mantine', isCaught: false },
  { name: 'skarmory', isCaught: false },
  { name: 'houndour', isCaught: false },
  { name: 'houndoom', isCaught: false },
  { name: 'kingdra', isCaught: false },
  { name: 'phanpy', isCaught: false },
  { name: 'donphan', isCaught: false },
  { name: 'porygon2', isCaught: false },
  { name: 'stantler', isCaught: false },
  { name: 'smeargle', isCaught: false },
  { name: 'tyrogue', isCaught: false },
  { name: 'hitmontop', isCaught: false },
  { name: 'smoochum', isCaught: false },
  { name: 'elekid', isCaught: false },
  { name: 'magby', isCaught: false },
  { name: 'miltank', isCaught: false },
  { name: 'blissey', isCaught: false },
  { name: 'raikou', isCaught: false },
  { name: 'entei', isCaught: false },
  { name: 'suicune', isCaught: false },
  { name: 'larvitar', isCaught: false },
  { name: 'pupitar', isCaught: false },
  { name: 'tyranitar', isCaught: false },
  { name: 'lugia', isCaught: false },
  { name: 'ho-oh', isCaught: false },
  { name: 'celebi', isCaught: false },
  { name: 'treecko', isCaught: false },
  { name: 'grovyle', isCaught: false },
  { name: 'sceptile', isCaught: false },
  { name: 'torchic', isCaught: false },
  { name: 'combusken', isCaught: false },
  { name: 'blaziken', isCaught: false },
  { name: 'mudkip', isCaught: false },
  { name: 'marshtomp', isCaught: false },
  { name: 'swampert', isCaught: false },
  { name: 'poochyena', isCaught: false },
  { name: 'mightyena', isCaught: false },
  { name: 'zigzagoon', isCaught: false },
  { name: 'linoone', isCaught: false },
  { name: 'wurmple', isCaught: false },
  { name: 'silcoon', isCaught: false },
  { name: 'beautifly', isCaught: false },
  { name: 'cascoon', isCaught: false },
  { name: 'dustox', isCaught: false },
  { name: 'lotad', isCaught: false },
  { name: 'lombre', isCaught: false },
  { name: 'ludicolo', isCaught: false },
  { name: 'seedot', isCaught: false },
  { name: 'nuzleaf', isCaught: false },
  { name: 'shiftry', isCaught: false },
  { name: 'taillow', isCaught: false },
  { name: 'swellow', isCaught: false },
  { name: 'wingull', isCaught: false },
  { name: 'pelipper', isCaught: false },
  { name: 'ralts', isCaught: false },
  { name: 'kirlia', isCaught: false },
  { name: 'gardevoir', isCaught: false },
  { name: 'surskit', isCaught: false },
  { name: 'masquerain', isCaught: false },
  { name: 'shroomish', isCaught: false },
  { name: 'breloom', isCaught: false },
  { name: 'slakoth', isCaught: false },
  { name: 'vigoroth', isCaught: false },
  { name: 'slaking', isCaught: false },
  { name: 'nincada', isCaught: false },
  { name: 'ninjask', isCaught: false },
  { name: 'shedinja', isCaught: false },
  { name: 'whismur', isCaught: false },
  { name: 'loudred', isCaught: false },
  { name: 'exploud', isCaught: false },
  { name: 'makuhita', isCaught: false },
  { name: 'hariyama', isCaught: false },
  { name: 'azurill', isCaught: false },
  { name: 'nosepass', isCaught: false },
  { name: 'skitty', isCaught: false },
  { name: 'delcatty', isCaught: false },
  { name: 'sableye', isCaught: false },
  { name: 'mawile', isCaught: false },
  { name: 'aron', isCaught: false },
  { name: 'lairon', isCaught: false },
  { name: 'aggron', isCaught: false },
  { name: 'meditite', isCaught: false },
  { name: 'medicham', isCaught: false },
  { name: 'electrike', isCaught: false },
  { name: 'manectric', isCaught: false },
  { name: 'plusle', isCaught: false },
  { name: 'minun', isCaught: false },
  { name: 'volbeat', isCaught: false },
  { name: 'illumise', isCaught: false },
  { name: 'roselia', isCaught: false },
  { name: 'gulpin', isCaught: false },
  { name: 'swalot', isCaught: false },
  { name: 'carvanha', isCaught: false },
  { name: 'sharpedo', isCaught: false },
  { name: 'wailmer', isCaught: false },
  { name: 'wailord', isCaught: false },
  { name: 'numel', isCaught: false },
  { name: 'camerupt', isCaught: false },
  { name: 'torkoal', isCaught: false },
  { name: 'spoink', isCaught: false },
  { name: 'grumpig', isCaught: false },
  { name: 'spinda', isCaught: false },
  { name: 'trapinch', isCaught: false },
  { name: 'vibrava', isCaught: false },
  { name: 'flygon', isCaught: false },
  { name: 'cacnea', isCaught: false },
  { name: 'cacturne', isCaught: false },
  { name: 'swablu', isCaught: false },
  { name: 'altaria', isCaught: false },
  { name: 'zangoose', isCaught: false },
  { name: 'seviper', isCaught: false },
  { name: 'lunatone', isCaught: false },
  { name: 'solrock', isCaught: false },
  { name: 'barboach', isCaught: false },
  { name: 'whiscash', isCaught: false },
  { name: 'corphish', isCaught: false },
  { name: 'crawdaunt', isCaught: false },
  { name: 'baltoy', isCaught: false },
  { name: 'claydol', isCaught: false },
  { name: 'lileep', isCaught: false },
  { name: 'cradily', isCaught: false },
  { name: 'anorith', isCaught: false },
  { name: 'armaldo', isCaught: false },
  { name: 'feebas', isCaught: false },
  { name: 'milotic', isCaught: false },
  { name: 'castform', isCaught: false },
  { name: 'kecleon', isCaught: false },
  { name: 'shuppet', isCaught: false },
  { name: 'banette', isCaught: false },
  { name: 'duskull', isCaught: false },
  { name: 'dusclops', isCaught: false },
  { name: 'tropius', isCaught: false },
  { name: 'chimecho', isCaught: false },
  { name: 'absol', isCaught: false },
  { name: 'wynaut', isCaught: false },
  { name: 'snorunt', isCaught: false },
  { name: 'glalie', isCaught: false },
  { name: 'spheal', isCaught: false },
  { name: 'sealeo', isCaught: false },
  { name: 'walrein', isCaught: false },
  { name: 'clamperl', isCaught: false },
  { name: 'huntail', isCaught: false },
  { name: 'gorebyss', isCaught: false },
  { name: 'relicanth', isCaught: false },
  { name: 'luvdisc', isCaught: false },
  { name: 'bagon', isCaught: false },
  { name: 'shelgon', isCaught: false },
  { name: 'salamence', isCaught: false },
  { name: 'beldum', isCaught: false },
  { name: 'metang', isCaught: false },
  { name: 'metagross', isCaught: false },
  { name: 'regirock', isCaught: false },
  { name: 'regice', isCaught: false },
  { name: 'registeel', isCaught: false },
  { name: 'latias', isCaught: false },
  { name: 'latios', isCaught: false },
  { name: 'kyogre', isCaught: false },
  { name: 'groudon', isCaught: false },
  { name: 'rayquaza', isCaught: false },
  { name: 'jirachi', isCaught: false },
  { name: 'deoxys-normal', isCaught: false },
  { name: 'turtwig', isCaught: false },
  { name: 'grotle', isCaught: false },
  { name: 'torterra', isCaught: false },
  { name: 'chimchar', isCaught: false },
  { name: 'monferno', isCaught: false },
  { name: 'infernape', isCaught: false },
  { name: 'piplup', isCaught: false },
  { name: 'prinplup', isCaught: false },
  { name: 'empoleon', isCaught: false },
  { name: 'starly', isCaught: false },
  { name: 'staravia', isCaught: false },
  { name: 'staraptor', isCaught: false },
  { name: 'bidoof', isCaught: false },
  { name: 'bibarel', isCaught: false },
  { name: 'kricketot', isCaught: false },
  { name: 'kricketune', isCaught: false },
  { name: 'shinx', isCaught: false },
  { name: 'luxio', isCaught: false },
  { name: 'luxray', isCaught: false },
  { name: 'budew', isCaught: false },
  { name: 'roserade', isCaught: false },
  { name: 'cranidos', isCaught: false },
  { name: 'rampardos', isCaught: false },
  { name: 'shieldon', isCaught: false },
  { name: 'bastiodon', isCaught: false },
  { name: 'burmy', isCaught: false },
  { name: 'wormadam-plant', isCaught: false },
  { name: 'mothim', isCaught: false },
  { name: 'combee', isCaught: false },
  { name: 'vespiquen', isCaught: false },
  { name: 'pachirisu', isCaught: false },
  { name: 'buizel', isCaught: false },
  { name: 'floatzel', isCaught: false },
  { name: 'cherubi', isCaught: false },
  { name: 'cherrim', isCaught: false },
  { name: 'shellos', isCaught: false },
  { name: 'gastrodon', isCaught: false },
  { name: 'ambipom', isCaught: false },
  { name: 'drifloon', isCaught: false },
  { name: 'drifblim', isCaught: false },
  { name: 'buneary', isCaught: false },
  { name: 'lopunny', isCaught: false },
  { name: 'mismagius', isCaught: false },
  { name: 'honchkrow', isCaught: false },
  { name: 'glameow', isCaught: false },
  { name: 'purugly', isCaught: false },
  { name: 'chingling', isCaught: false },
  { name: 'stunky', isCaught: false },
  { name: 'skuntank', isCaught: false },
  { name: 'bronzor', isCaught: false },
  { name: 'bronzong', isCaught: false },
  { name: 'bonsly', isCaught: false },
  { name: 'mime-jr', isCaught: false },
  { name: 'happiny', isCaught: false },
  { name: 'chatot', isCaught: false },
  { name: 'spiritomb', isCaught: false },
  { name: 'gible', isCaught: false },
  { name: 'gabite', isCaught: false },
  { name: 'garchomp', isCaught: false },
  { name: 'munchlax', isCaught: false },
  { name: 'riolu', isCaught: false },
  { name: 'lucario', isCaught: false },
  { name: 'hippopotas', isCaught: false },
  { name: 'hippowdon', isCaught: false },
  { name: 'skorupi', isCaught: false },
  { name: 'drapion', isCaught: false },
  { name: 'croagunk', isCaught: false },
  { name: 'toxicroak', isCaught: false },
  { name: 'carnivine', isCaught: false },
  { name: 'finneon', isCaught: false },
  { name: 'lumineon', isCaught: false },
  { name: 'mantyke', isCaught: false },
  { name: 'snover', isCaught: false },
  { name: 'abomasnow', isCaught: false },
  { name: 'weavile', isCaught: false },
  { name: 'magnezone', isCaught: false },
  { name: 'lickilicky', isCaught: false },
  { name: 'rhyperior', isCaught: false },
  { name: 'tangrowth', isCaught: false },
  { name: 'electivire', isCaught: false },
  { name: 'magmortar', isCaught: false },
  { name: 'togekiss', isCaught: false },
  { name: 'yanmega', isCaught: false },
  { name: 'leafeon', isCaught: false },
  { name: 'glaceon', isCaught: false },
  { name: 'gliscor', isCaught: false },
  { name: 'mamoswine', isCaught: false },
  { name: 'porygon-z', isCaught: false },
  { name: 'gallade', isCaught: false },
  { name: 'probopass', isCaught: false },
  { name: 'dusknoir', isCaught: false },
  { name: 'froslass', isCaught: false },
  { name: 'rotom', isCaught: false },
  { name: 'uxie', isCaught: false },
  { name: 'mesprit', isCaught: false },
  { name: 'azelf', isCaught: false },
  { name: 'dialga', isCaught: false },
  { name: 'palkia', isCaught: false },
  { name: 'heatran', isCaught: false },
  { name: 'regigigas', isCaught: false },
  { name: 'giratina-altered', isCaught: false },
  { name: 'cresselia', isCaught: false },
  { name: 'phione', isCaught: false },
  { name: 'manaphy', isCaught: false },
  { name: 'darkrai', isCaught: false },
  { name: 'shaymin-land', isCaught: false },
  { name: 'arceus', isCaught: false },
  { name: 'victini', isCaught: false },
  { name: 'snivy', isCaught: false },
  { name: 'servine', isCaught: false },
  { name: 'serperior', isCaught: false },
  { name: 'tepig', isCaught: false },
  { name: 'pignite', isCaught: false },
  { name: 'emboar', isCaught: false },
  { name: 'oshawott', isCaught: false },
  { name: 'dewott', isCaught: false },
  { name: 'samurott', isCaught: false },
  { name: 'patrat', isCaught: false },
  { name: 'watchog', isCaught: false },
  { name: 'lillipup', isCaught: false },
  { name: 'herdier', isCaught: false },
  { name: 'stoutland', isCaught: false },
  { name: 'purrloin', isCaught: false },
  { name: 'liepard', isCaught: false },
  { name: 'pansage', isCaught: false },
  { name: 'simisage', isCaught: false },
  { name: 'pansear', isCaught: false },
  { name: 'simisear', isCaught: false },
  { name: 'panpour', isCaught: false },
  { name: 'simipour', isCaught: false },
  { name: 'munna', isCaught: false },
  { name: 'musharna', isCaught: false },
  { name: 'pidove', isCaught: false },
  { name: 'tranquill', isCaught: false },
  { name: 'unfezant', isCaught: false },
  { name: 'blitzle', isCaught: false },
  { name: 'zebstrika', isCaught: false },
  { name: 'roggenrola', isCaught: false },
  { name: 'boldore', isCaught: false },
  { name: 'gigalith', isCaught: false },
  { name: 'woobat', isCaught: false },
  { name: 'swoobat', isCaught: false },
  { name: 'drilbur', isCaught: false },
  { name: 'excadrill', isCaught: false },
  { name: 'audino', isCaught: false },
  { name: 'timburr', isCaught: false },
  { name: 'gurdurr', isCaught: false },
  { name: 'conkeldurr', isCaught: false },
  { name: 'tympole', isCaught: false },
  { name: 'palpitoad', isCaught: false },
  { name: 'seismitoad', isCaught: false },
  { name: 'throh', isCaught: false },
  { name: 'sawk', isCaught: false },
  { name: 'sewaddle', isCaught: false },
  { name: 'swadloon', isCaught: false },
  { name: 'leavanny', isCaught: false },
  { name: 'venipede', isCaught: false },
  { name: 'whirlipede', isCaught: false },
  { name: 'scolipede', isCaught: false },
  { name: 'cottonee', isCaught: false },
  { name: 'whimsicott', isCaught: false },
  { name: 'petilil', isCaught: false },
  { name: 'lilligant', isCaught: false },
  { name: 'basculin-red-striped', isCaught: false },
  { name: 'sandile', isCaught: false },
  { name: 'krokorok', isCaught: false },
  { name: 'krookodile', isCaught: false },
  { name: 'darumaka', isCaught: false },
  { name: 'darmanitan-standard', isCaught: false },
  { name: 'maractus', isCaught: false },
  { name: 'dwebble', isCaught: false },
  { name: 'crustle', isCaught: false },
  { name: 'scraggy', isCaught: false },
  { name: 'scrafty', isCaught: false },
  { name: 'sigilyph', isCaught: false },
  { name: 'yamask', isCaught: false },
  { name: 'cofagrigus', isCaught: false },
  { name: 'tirtouga', isCaught: false },
  { name: 'carracosta', isCaught: false },
  { name: 'archen', isCaught: false },
  { name: 'archeops', isCaught: false },
  { name: 'trubbish', isCaught: false },
  { name: 'garbodor', isCaught: false },
  { name: 'zorua', isCaught: false },
  { name: 'zoroark', isCaught: false },
  { name: 'minccino', isCaught: false },
  { name: 'cinccino', isCaught: false },
  { name: 'gothita', isCaught: false },
  { name: 'gothorita', isCaught: false },
  { name: 'gothitelle', isCaught: false },
  { name: 'solosis', isCaught: false },
  { name: 'duosion', isCaught: false },
  { name: 'reuniclus', isCaught: false },
  { name: 'ducklett', isCaught: false },
  { name: 'swanna', isCaught: false },
  { name: 'vanillite', isCaught: false },
  { name: 'vanillish', isCaught: false },
  { name: 'vanilluxe', isCaught: false },
  { name: 'deerling', isCaught: false },
  { name: 'sawsbuck', isCaught: false },
  { name: 'emolga', isCaught: false },
  { name: 'karrablast', isCaught: false },
  { name: 'escavalier', isCaught: false },
  { name: 'foongus', isCaught: false },
  { name: 'amoonguss', isCaught: false },
  { name: 'frillish', isCaught: false },
  { name: 'jellicent', isCaught: false },
  { name: 'alomomola', isCaught: false },
  { name: 'joltik', isCaught: false },
  { name: 'galvantula', isCaught: false },
  { name: 'ferroseed', isCaught: false },
  { name: 'ferrothorn', isCaught: false },
  { name: 'klink', isCaught: false },
  { name: 'klang', isCaught: false },
  { name: 'klinklang', isCaught: false },
  { name: 'tynamo', isCaught: false },
  { name: 'eelektrik', isCaught: false },
  { name: 'eelektross', isCaught: false },
  { name: 'elgyem', isCaught: false },
  { name: 'beheeyem', isCaught: false },
  { name: 'litwick', isCaught: false },
  { name: 'lampent', isCaught: false },
  { name: 'chandelure', isCaught: false },
  { name: 'axew', isCaught: false },
  { name: 'fraxure', isCaught: false },
  { name: 'haxorus', isCaught: false },
  { name: 'cubchoo', isCaught: false },
  { name: 'beartic', isCaught: false },
  { name: 'cryogonal', isCaught: false },
  { name: 'shelmet', isCaught: false },
  { name: 'accelgor', isCaught: false },
  { name: 'stunfisk', isCaught: false },
  { name: 'mienfoo', isCaught: false },
  { name: 'mienshao', isCaught: false },
  { name: 'druddigon', isCaught: false },
  { name: 'golett', isCaught: false },
  { name: 'golurk', isCaught: false },
  { name: 'pawniard', isCaught: false },
  { name: 'bisharp', isCaught: false },
  { name: 'bouffalant', isCaught: false },
  { name: 'rufflet', isCaught: false },
  { name: 'braviary', isCaught: false },
  { name: 'vullaby', isCaught: false },
  { name: 'mandibuzz', isCaught: false },
  { name: 'heatmor', isCaught: false },
  { name: 'durant', isCaught: false },
  { name: 'deino', isCaught: false },
  { name: 'zweilous', isCaught: false },
  { name: 'hydreigon', isCaught: false },
  { name: 'larvesta', isCaught: false },
  { name: 'volcarona', isCaught: false },
  { name: 'cobalion', isCaught: false },
  { name: 'terrakion', isCaught: false },
  { name: 'virizion', isCaught: false },
  { name: 'tornadus-incarnate', isCaught: false },
  { name: 'thundurus-incarnate', isCaught: false },
  { name: 'reshiram', isCaught: false },
  { name: 'zekrom', isCaught: false },
  { name: 'landorus-incarnate', isCaught: false },
  { name: 'kyurem', isCaught: false },
  { name: 'keldeo-ordinary', isCaught: false },
  { name: 'meloetta-aria', isCaught: false },
  { name: 'genesect', isCaught: false },
  { name: 'chespin', isCaught: false },
  { name: 'quilladin', isCaught: false },
  { name: 'chesnaught', isCaught: false },
  { name: 'fennekin', isCaught: false },
  { name: 'braixen', isCaught: false },
  { name: 'delphox', isCaught: false },
  { name: 'froakie', isCaught: false },
  { name: 'frogadier', isCaught: false },
  { name: 'greninja', isCaught: false },
  { name: 'bunnelby', isCaught: false },
  { name: 'diggersby', isCaught: false },
  { name: 'fletchling', isCaught: false },
  { name: 'fletchinder', isCaught: false },
  { name: 'talonflame', isCaught: false },
  { name: 'scatterbug', isCaught: false },
  { name: 'spewpa', isCaught: false },
  { name: 'vivillon', isCaught: false },
  { name: 'litleo', isCaught: false },
  { name: 'pyroar', isCaught: false },
  { name: 'flabebe', isCaught: false },
  { name: 'floette', isCaught: false },
  { name: 'florges', isCaught: false },
  { name: 'skiddo', isCaught: false },
  { name: 'gogoat', isCaught: false },
  { name: 'pancham', isCaught: false },
  { name: 'pangoro', isCaught: false },
  { name: 'furfrou', isCaught: false },
  { name: 'espurr', isCaught: false },
  { name: 'meowstic-male', isCaught: false },
  { name: 'honedge', isCaught: false },
  { name: 'doublade', isCaught: false },
  { name: 'aegislash-shield', isCaught: false },
  { name: 'spritzee', isCaught: false },
  { name: 'aromatisse', isCaught: false },
  { name: 'swirlix', isCaught: false },
  { name: 'slurpuff', isCaught: false },
  { name: 'inkay', isCaught: false },
  { name: 'malamar', isCaught: false },
  { name: 'binacle', isCaught: false },
  { name: 'barbaracle', isCaught: false },
  { name: 'skrelp', isCaught: false },
  { name: 'dragalge', isCaught: false },
  { name: 'clauncher', isCaught: false },
  { name: 'clawitzer', isCaught: false },
  { name: 'helioptile', isCaught: false },
  { name: 'heliolisk', isCaught: false },
  { name: 'tyrunt', isCaught: false },
  { name: 'tyrantrum', isCaught: false },
  { name: 'amaura', isCaught: false },
  { name: 'aurorus', isCaught: false },
  { name: 'sylveon', isCaught: false },
  { name: 'hawlucha', isCaught: false },
  { name: 'dedenne', isCaught: false },
  { name: 'carbink', isCaught: false },
  { name: 'goomy', isCaught: false },
  { name: 'sliggoo', isCaught: false },
  { name: 'goodra', isCaught: false },
  { name: 'klefki', isCaught: false },
  { name: 'phantump', isCaught: false },
  { name: 'trevenant', isCaught: false },
  { name: 'pumpkaboo-average', isCaught: false },
  { name: 'gourgeist-average', isCaught: false },
  { name: 'bergmite', isCaught: false },
  { name: 'avalugg', isCaught: false },
  { name: 'noibat', isCaught: false },
  { name: 'noivern', isCaught: false },
  { name: 'xerneas', isCaught: false },
  { name: 'yveltal', isCaught: false },
  { name: 'zygarde', isCaught: false },
  { name: 'diancie', isCaught: false },
  { name: 'hoopa', isCaught: false },
  { name: 'volcanion', isCaught: false },
  { name: 'rowlet', isCaught: false },
  { name: 'dartrix', isCaught: false },
  { name: 'decidueye', isCaught: false },
  { name: 'litten', isCaught: false },
  { name: 'torracat', isCaught: false },
  { name: 'incineroar', isCaught: false },
  { name: 'popplio', isCaught: false },
  { name: 'brionne', isCaught: false },
  { name: 'primarina', isCaught: false },
  { name: 'pikipek', isCaught: false },
  { name: 'trumbeak', isCaught: false },
  { name: 'toucannon', isCaught: false },
  { name: 'yungoos', isCaught: false },
  { name: 'gumshoos', isCaught: false },
  { name: 'grubbin', isCaught: false },
  { name: 'charjabug', isCaught: false },
  { name: 'vikavolt', isCaught: false },
  { name: 'crabrawler', isCaught: false },
  { name: 'crabominable', isCaught: false },
  { name: 'oricorio-baile', isCaught: false },
  { name: 'cutiefly', isCaught: false },
  { name: 'ribombee', isCaught: false },
  { name: 'rockruff', isCaught: false },
  { name: 'lycanroc-midday', isCaught: false },
  { name: 'wishiwashi-solo', isCaught: false },
  { name: 'mareanie', isCaught: false },
  { name: 'toxapex', isCaught: false },
  { name: 'mudbray', isCaught: false },
  { name: 'mudsdale', isCaught: false },
  { name: 'dewpider', isCaught: false },
  { name: 'araquanid', isCaught: false },
  { name: 'fomantis', isCaught: false },
  { name: 'lurantis', isCaught: false },
  { name: 'morelull', isCaught: false },
  { name: 'shiinotic', isCaught: false },
  { name: 'salandit', isCaught: false },
  { name: 'salazzle', isCaught: false },
  { name: 'stufful', isCaught: false },
  { name: 'bewear', isCaught: false },
  { name: 'bounsweet', isCaught: false },
  { name: 'steenee', isCaught: false },
  { name: 'tsareena', isCaught: false },
  { name: 'comfey', isCaught: false },
  { name: 'oranguru', isCaught: false },
  { name: 'passimian', isCaught: false },
  { name: 'wimpod', isCaught: false },
  { name: 'golisopod', isCaught: false },
  { name: 'sandygast', isCaught: false },
  { name: 'palossand', isCaught: false },
  { name: 'pyukumuku', isCaught: false },
  { name: 'type-null', isCaught: false },
  { name: 'silvally', isCaught: false },
  { name: 'minior-red-meteor', isCaught: false },
  { name: 'komala', isCaught: false },
  { name: 'turtonator', isCaught: false },
  { name: 'togedemaru', isCaught: false },
  { name: 'mimikyu-disguised', isCaught: false },
  { name: 'bruxish', isCaught: false },
  { name: 'drampa', isCaught: false },
  { name: 'dhelmise', isCaught: false },
  { name: 'jangmo-o', isCaught: false },
  { name: 'hakamo-o', isCaught: false },
  { name: 'kommo-o', isCaught: false },
  { name: 'tapu-koko', isCaught: false },
  { name: 'tapu-lele', isCaught: false },
  { name: 'tapu-bulu', isCaught: false },
  { name: 'tapu-fini', isCaught: false },
  { name: 'cosmog', isCaught: false },
  { name: 'cosmoem', isCaught: false },
  { name: 'solgaleo', isCaught: false },
  { name: 'lunala', isCaught: false },
  { name: 'nihilego', isCaught: false },
  { name: 'buzzwole', isCaught: false },
  { name: 'pheromosa', isCaught: false },
  { name: 'xurkitree', isCaught: false },
  { name: 'celesteela', isCaught: false },
  { name: 'kartana', isCaught: false },
  { name: 'guzzlord', isCaught: false },
  { name: 'necrozma', isCaught: false },
  { name: 'magearna', isCaught: false },
  { name: 'marshadow', isCaught: false },
  { name: 'poipole', isCaught: false },
  { name: 'naganadel', isCaught: false },
  { name: 'stakataka', isCaught: false },
  { name: 'blacephalon', isCaught: false },
  { name: 'zeraora', isCaught: false },
  { name: 'meltan', isCaught: false },
  { name: 'melmetal', isCaught: false },
];

export const GEN1_FILTER = NEW_USER.slice(0, GenEnum.GEN_1 - 1);
export const GEN2_FILTER = NEW_USER.slice(GenEnum.GEN_1, GenEnum.GEN_2 - 1);
export const GEN3_FILTER = NEW_USER.slice(GenEnum.GEN_2, GenEnum.GEN_3 - 1);

export const RIVAL_LIST = [
  {
    name: 'blue',
    path: 'src/assets/rivals/blue.webp',
    pokemon: [
      { id: 3, name: 'venusaur', isStarter: true },
      { id: 18, name: 'pidgeot', isStarter: false },
      { id: 59, name: 'arcanine', isStarter: true },
      { id: 65, name: 'alakazam', isStarter: false },
      { id: 103, name: 'exeggutor', isStarter: false },
      { id: 112, name: 'rhydon', isStarter: false },
      { id: 130, name: 'gyarados', isStarter: true },
      { id: 135, name: 'jolteon', isStarter: false },
      { id: 142, name: 'aerodactyl', isStarter: false },
      { id: 214, name: 'heracross', isStarter: false },
      { id: 248, name: 'tyranitar', isStarter: false },
    ],
  },
  {
    name: 'red',
    path: 'src/assets/rivals/red.webp',
    pokemon: [
      { id: 3, name: 'venusaur', isStarter: false },
      { id: 6, name: 'charizard', isStarter: true },
      { id: 9, name: 'blastoise', isStarter: false },
      { id: 25, name: 'pikachu', isStarter: true },
      { id: 68, name: 'machamp', isStarter: false },
      { id: 131, name: 'lapras', isStarter: true },
      { id: 143, name: 'snorlax', isStarter: false },
      { id: 196, name: 'espeon', isStarter: false },
    ],
  },
  {
    name: 'lance',
    path: 'src/assets/rivals/lance.webp',
    pokemon: [
      { id: 6, name: 'charizard', isStarter: false },
      { id: 130, name: 'gyarados', isStarter: true },
      { id: 142, name: 'aerodactyl', isStarter: false },
      { id: 148, name: 'dragonair', isStarter: false },
      { id: 149, name: 'dragonite', isStarter: true },
      { id: 230, name: 'kingdra', isStarter: false },
      { id: 248, name: 'tyranitar', isStarter: false },
      { id: 330, name: 'flygon', isStarter: false },
      { id: 373, name: 'salamence', isStarter: false },
      { id: 445, name: 'garchomp', isStarter: true },
      { id: 612, name: 'haxorus', isStarter: false },
      { id: 635, name: 'hydreigon', isStarter: false },
    ],
  },
  {
    name: 'giovanni',
    path: 'src/assets/rivals/gio.webp',
    pokemon: [
      { id: 28, name: 'sandslash', isStarter: false },
      { id: 31, name: 'nidoqueen', isStarter: true },
      { id: 34, name: 'nidoking', isStarter: true },
      { id: 53, name: 'persian', isStarter: false },
      { id: 51, name: 'dugtrio', isStarter: false },
      { id: 76, name: 'golem', isStarter: false },
      { id: 105, name: 'marowak', isStarter: false },
      { id: 112, name: 'rhydon', isStarter: true },
      { id: 115, name: 'kangaskhan', isStarter: false },
      { id: 430, name: 'honchkrow', isStarter: false },
      { id: 445, name: 'garchomp', isStarter: false },
      { id: 450, name: 'hippowdon', isStarter: false },
      { id: 464, name: 'rhyperior', isStarter: false },
      { id: 472, name: 'gliscor', isStarter: false },
      { id: 553, name: 'krookodile', isStarter: false },
    ],
  },
  // {
  //   name: 'simo',
  //   path: 'src/assets/rivals/cool.webp',
  //   pokemon: [
  //     { id: 76, name: 'golem', isStarter: false },
  //     { id: 94, name: 'gengar', isStarter: true },
  //     { id: 101, name: 'electrode', isStarter: true },
  //     { id: 128, name: 'tauros', isStarter: false },
  //     { id: 136, name: 'flareon', isStarter: true },
  //     { id: 148, name: 'dragonair', isStarter: false },
  //     { id: 181, name: 'ampharos', isStarter: false },
  //     { id: 214, name: 'heracross', isStarter: false },
  //     { id: 248, name: 'tyranitar', isStarter: false },
  //     { id: 330, name: 'flygon', isStarter: false },
  //     { id: 450, name: 'hippowdon', isStarter: false },
  //   ],
  // },
  {
    name: 'byers',
    path: 'src/assets/rivals/acef.webp',
    pokemon: [
      { id: 38, name: 'ninetales', isStarter: true },
      { id: 39, name: 'jigglypuff', isStarter: false },
      { id: 114, name: 'tangela', isStarter: true },
      { id: 130, name: 'gyarados', isStarter: false },
      { id: 132, name: 'ditto', isStarter: false },
      { id: 134, name: 'vaporeon', isStarter: false },
      { id: 175, name: 'togepi', isStarter: true },
      { id: 726, name: 'torracat', isStarter: false },
    ],
  },
  {
    name: 'kautz',
    path: 'src/assets/rivals/hiker.webp',
    pokemon: [
      { id: 7, name: 'squirtle', isStarter: true },
      { id: 137, name: 'porygon', isStarter: true },
      { id: 151, name: 'mew', isStarter: true },
      { id: 158, name: 'totodile', isStarter: false },
      { id: 206, name: 'dunsparce', isStarter: false },
      { id: 235, name: 'smeargle', isStarter: false },
      { id: 241, name: 'miltank', isStarter: false },
      { id: 251, name: 'celebi', isStarter: false },
      { id: 350, name: 'milotic', isStarter: false },
      { id: 385, name: 'jirachi', isStarter: false },
    ],
  },
];

export const STAT_MAX = {
  Hp: 255,
  Atk: 190,
  Def: 250,
  SpA: 194,
  SpD: 250,
  Speed: 200,
};
